### ISSUE TITLE
Decision post about "atomic commits/PRs" and Conventional commits/branches

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/decisions#17] opened 2024-02-01 19:20 UTC
We are already doing this but should have a decision post about it.

**Comment by henrik-goul** [comment] 2024-05-02 13:05
@lwjohnst86 I assume that this task was assigned to me by mistake ;)

**Comment by lwjohnst86** [comment] 2024-05-02 14:04
Ha yes you are right haha

**Comment by signekb** [comment] 2024-05-14 11:27
This is a duplicate of seedcase-project/team#39, seedcase-project/team#90, seedcase-project/team#91.

**Closed by signekb** 2024-05-14 11:27 UTC
